.microsoft-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/microsoft ]  # 1. Is disabled, never run
      when: never
    - changes:
        paths: [ .ci-farms-disabled/microsoft ]  # 2. Removed from disabled, run
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]  # 3. We touched other farms in MR, do not run
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    # 4. Fall-through (other rules or on_success)

.microsoft-farm-manual-rules:
  rules:
    # Allow triggering jobs manually in other cases if any files affecting the
    # pipeline were changed
    - exists: [ .ci-farms-disabled/microsoft ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/microsoft ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.microsoft-farm-rules, rules]

.microsoft-farm-container-rules:
  rules:
    # Allow triggering jobs manually in other cases if any files affecting the
    # pipeline were changed
    - exists: [ .ci-farms-disabled/microsoft ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/microsoft ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - !reference [.microsoft-farm-rules, rules]


.collabora-farm-rules:
  rules:
    - if: '$RUNNER_TAG =~ /^mesa-ci-x86-64-lava-/'
      exists: [ .ci-farms-disabled/collabora ]
      when: never
    - if: '$RUNNER_TAG =~ /^mesa-ci-x86-64-lava-/ && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        paths: [ .ci-farms-disabled/collabora ]
        compare_to: main
      when: on_success
    - if: '$RUNNER_TAG =~ /^mesa-ci-x86-64-lava-/ && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      when: never

.collabora-farm-manual-rules:
  rules:
    - if: '$RUNNER_TAG =~ /^mesa-ci-x86-64-lava-/'
      exists: [ .ci-farms-disabled/collabora ]
      when: never
    - if: '$RUNNER_TAG =~ /^mesa-ci-x86-64-lava-/ && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        paths: [ .ci-farms-disabled/collabora ]
        compare_to: main
      when: never
    - !reference [.collabora-farm-rules, rules]


.igalia-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/igalia ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/igalia ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never

.igalia-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/igalia ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/igalia ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.igalia-farm-rules, rules]


.lima-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/lima ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/lima ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never

.lima-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/lima ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/lima ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.lima-farm-rules, rules]


.anholt-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/anholt ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/anholt ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never

.anholt-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/anholt ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/anholt ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.anholt-farm-rules, rules]


.valve-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/valve-mupuf ]
      if: '$RUNNER_FARM_LOCATION == "mupuf"'
      when: never
    - exists: [ .ci-farms-disabled/valve-kws ]
      if: '$RUNNER_FARM_LOCATION == "keywords"'
      when: never
    - changes:
        paths: [ .ci-farms-disabled/valve-mupuf ]
        compare_to: main
      if: '$RUNNER_FARM_LOCATION == "mupuf" && $CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/valve-kws ]
        compare_to: main
      if: '$RUNNER_FARM_LOCATION == "keywords" && $CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      when: never

.valve-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/valve-mupuf ]
      if: '$RUNNER_FARM_LOCATION == "mupuf"'
      when: never
    - exists: [ .ci-farms-disabled/valve-kws ]
      if: '$RUNNER_FARM_LOCATION == "keywords"'
      when: never
    - changes:
        paths: [ .ci-farms-disabled/valve-mupuf ]
        compare_to: main
      if: '$RUNNER_FARM_LOCATION == "mupuf" && $CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - changes:
        paths: [ .ci-farms-disabled/valve-kws ]
        compare_to: main
      if: '$RUNNER_FARM_LOCATION == "keywords" && $CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.valve-farm-rules, rules]


.austriancoder-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/austriancoder ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/austriancoder ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never

.austriancoder-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/austriancoder ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/austriancoder ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.austriancoder-farm-rules, rules]


.freedreno-farm-rules:
  rules:
    - exists: [ .ci-farms-disabled/freedreno ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/freedreno ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - changes:
        paths: [ .ci-farms-disabled/* ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never

.freedreno-farm-manual-rules:
  rules:
    - exists: [ .ci-farms-disabled/freedreno ]
      when: never
    - changes:
        paths: [ .ci-farms-disabled/freedreno ]
        compare_to: main
      if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: never
    - !reference [.freedreno-farm-rules, rules]

